name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: protobuf

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19.x
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install packages
        run: |
          make install
      - name: Run linters
        run: |
          make lint
